# Generated by Django 4.1 on 2022-08-16 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_category', models.CharField(max_length=50)),
                ('item_cost', models.FloatField()),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=10)),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.item')),
            ],
        ),
    ]
